# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Discount'), (1, 'Cumulative')], default=0),
            preserve_default=False,
        ),
    ]
