# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20160622_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='profile',
            new_name='user',
        ),
    ]
